# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_arg_encoder <- function() {
    .Call('_fun_club_new_arg_encoder', PACKAGE = 'fun.club')
}

add_arg <- function(xptr, fo, arg, printable_arg) {
    .Call('_fun_club_add_arg', PACKAGE = 'fun.club', xptr, fo, arg, printable_arg)
}

ind_arg <- function(xptr, fo, arg) {
    .Call('_fun_club_ind_arg', PACKAGE = 'fun.club', xptr, fo, arg)
}

printable_arg <- function(xptr, fo, ind) {
    .Call('_fun_club_printable_arg', PACKAGE = 'fun.club', xptr, fo, ind)
}

serialized_arg <- function(xptr, fo, ind) {
    .Call('_fun_club_serialized_arg', PACKAGE = 'fun.club', xptr, fo, ind)
}

rm_arg <- function(xptr, fo, ind) {
    .Call('_fun_club_rm_arg', PACKAGE = 'fun.club', xptr, fo, ind)
}

load_fo_arg <- function(xptr, fo_name, args, printable_args, inds) {
    invisible(.Call('_fun_club_load_fo_arg', PACKAGE = 'fun.club', xptr, fo_name, args, printable_args, inds))
}

load_arg <- function(arg_encoder) {
    .Call('_fun_club_load_arg', PACKAGE = 'fun.club', arg_encoder)
}

dump_arg <- function(xptr) {
    .Call('_fun_club_dump_arg', PACKAGE = 'fun.club', xptr)
}

print_arg <- function(xptr) {
    invisible(.Call('_fun_club_print_arg', PACKAGE = 'fun.club', xptr))
}

clear_arg <- function(xptr) {
    invisible(.Call('_fun_club_clear_arg', PACKAGE = 'fun.club', xptr))
}

